### ISSUE TITLE
Dry Hootch  Dashboard org ID 9199

### ISSUE THREAD

**Issue by RobertZiemba** [DonorPath/DonorPath.MeetUp#5]
Hello Reid,

When I try and load  the dashboard nearly 28 different segments are on the left side . There is no file that was uploaded to this dashboard  to my knowledge ( new org) when I went to the segments section I received an error.  
![untitled](https://cloud.githubusercontent.com/assets/20076543/17028885/a81270ce-4f2e-11e6-974c-33bc3e318779.png)

Can you just reset this dashboard

Thanks,

Robert

**Comment by reidcompton** [comment]
Dashboard is reset. Also, we've got a couple of different code repositories, the one for the product is - https://github.com/DonorPath/DonorPath.App

**Comment by RobertZiemba** [comment]
Hello Reid,

Thanks for solving the issues and when I try to acess that page  I receive an error[cid:fb7021fb-2473-4808-b0be-2afad5101f96]

**Comment by reidcompton** [comment]
## Ok, looks like your invite into our GitHub organization is still pending. I canceled the invite and sent it again. Once you accept it, you’ll be able to see the DonorPath.App repository.

Reid Compton
Developer

   DonorPath
   105 W Adams Suite 2940
   Chicago, IL 60603

```
M | 727.244.7420

www.donorpath.org
```

**Comment by RobertZiemba** [comment]
I am in there now

Thanks
